---
- name: Configure Jenkins Playbook
  hosts: all
  gather_facts: False
  remote_user: ubuntu
  become: true
  vars_files:
  - "vars.yml"
  pre_tasks:
  - include_tasks: roles/python.yml

#  - name: Install packages and dependencies
#    apt:
#     name = {{ item }}
#     state = present
#     install_recommends=yes
#     update_cache=yes
#    with_items:
#     - libfontconfig
#     - libffi-dev
#     - libncurses5-dev
#     - default-jre

  - name: Install Java
    apt:
     name=default-jre
     install_recommends=yes
     state=present

  - name: Add the Jenkins public GPG key to the apt repo
    apt_key:
     url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
     state=present

  - name: Add Jenkins to the trusted sources list
    apt_repository:
     repo='deb http://pkg.jenkins-ci.org/debian binary/'
     state=present

  tasks:
  - name: Install Jenkins
    apt:
     name=jenkins
     state=present
     install_recommends=yes
     update_cache=yes

  - include_role:
     name: nginx
